[package]
name = "brane-sys"
version = "0.1.0"
authors = ["Onno Valkering"]
edition = "2018"

[dependencies]
anyhow = "1.0"
appdirs = "0.2"
futures = "0.3"
lazy_static = "1.4"
log = "0.4"
specifications = { path = "../specifications" }
url = "2.1"
uuid = { version = "0.8", features = ["v4"] }
