openapi: 3.0.3
info:
  title: Vantage6
  version: 0.1.0
  description: The Vantage6 API.

servers:
  - url: http://localhost:5000/api

paths:
  "/collaboration":
    get:
      operationId: getCollaborations
      responses:
        "200":
          description: OK, array of collaborations
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Collaboration"
      security:
        - bearerAuth: []

  "/token/user":
    post:
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/User"
      responses:
        '200':
          description: OK, authenticated
          content:
            application/json:
              schema:
                type: object
                required:
                  - access_token
                  - refresh_token
                  - refresh_url
                  - user_url
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  refresh_url:
                    type: string
                  user_url:
                    type: string

components:
  schemas:
    Collaboration:
      properties:
        id:
          type: integer
        name:
          type: string
        encrypted:
          type: boolean

    User:
      properties:
        username:
          type: string
        password:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
