version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Cargo version update
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    # Limit is arbitrary, but having a slight limit helps keeps stuff managable
    open-pull-requests-limit: 5
    groups:
      backwards-compatible:
        update-types:
          - "patch"
          - "minor"
