version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Cargo version update
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    # Limit is arbitrary, but having a slight limit helps keeps stuff manageable
    open-pull-requests-limit: 5
    groups:
      # The policy reasoner functions as a whole, lets attempt to update it as a whole
      policy-reasoner:
        patterns:
          - "auth-resolver"
          - "deliberation"
          - "eflint-to-json"
          - "policy"
          - "reasonerconn"
          - "srv"
          - "state-resolver"
          - "workflow"
          - "audit-logger"
          - "nested-cli-parser"
          # Tools
          - "checker-client"
          - "key-manager"
          - "policy-builder"

      backwards-compatible:
        update-types:
          - "patch"
          - "minor"
    # Okay this might seem odd, but right now Dependabot does not respect
    # minimal versions and attempts to update the minimal version at every
    # update. We can circumvent this by telling to only every update lockfiles,
    # however this would be incorrect for major versions. To make matters worse,
    # working around this problem by making two separate disjoint rules for major
    # and minor/patch will not work either, as it will refuse because Dependabot
    # is unable to recognize that they are in fact disjoint.
    #
    # The most sane compromise is to let Dependabot only handle version updates
    # for patch and minor versions, and keep track of major version updates by
    # some other means.
    #
    # Relevant open issues:
    # - Incorrect manifest behaviour: https://github.com/Dependabot/Dependabot-core/issues/4009
    # - Disjoint overlapping rules: https://github.com/Dependabot/Dependabot-core/issues/10160
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    versioning-strategy: "lockfile-only"
