[formatting]
align_comments = true
align_entries = false
allowed_blank_lines = 2
array_auto_collapse = true
array_auto_expand = true
array_trailing_comma = true
column_width = 120
compact_arrays = true
compact_entries = false
compact_inline_tables = false
crlf = false
indent_entries = false
indent_string = "    "
indent_tables = false
inline_table_expand = true
reorder_arrays = false
reorder_inline_tables = false
reorder_keys = false
trailing_newline = true

# Taplo: Force order of formatter settings
[[rule]]
include = [".taplo.toml", "taplo.toml"]
keys = ["formatting"]
formatting = { reorder_keys = true }

# Cargo: Sort dependencies
[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "workspace.dependencies"]
formatting = { reorder_keys = true }

# Cargo: Sort workspace members
[[rule]]
include = ["**/Cargo.toml"]
keys = ["workspace.members"]
formatting = { reorder_array = true }

# Cargo deny: Sort allowed licenses
[[rule]]
include = ["deny.toml"]
keys = ["licenses"]
formatting = { reorder_arrays = true }
