language: rust
os: linux
dist: bionic

addons:
  apt:
    packages:
      - libpq-dev
      - libssl-dev

cache: cargo

before_script:
  - cargo install cargo-tarpaulin

script:
  - cargo clean
  - cargo build
  - cargo test

after_success:
  - cargo tarpaulin --workspace --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
