language: rust
dist: focal

addons:
  apt:
    packages:
      - libpq-dev
      - libssl-dev

cache: cargo

before_script:
  - rustup component add rustfmt
  - cargo install cargo-tarpaulin
  - pushd ./contrib/datastax && sudo make && popd

script:
  - cargo build

after_success:
  - cargo tarpaulin --workspace --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
