[workspace]
members = [
    "brane-api",
    "brane-bvm",
    "brane-cfg",
    "brane-clb",
    "brane-cli",
    "brane-dsl",
    "brane-job",
    "brane-log",
    "brane-let",
    "brane-oas",
    "specifications",
]

# Keep it seperate: conflicting dependencies.
exclude = [
    "brane-net"
]
