[workspace]
resolver = "2"
members = [
    ### OVERVIEW ###
    "overview",


    ### BINARIES ###
    # These crates directly relate to the CTL tool
    "brane-ctl",

    # These crates directly relate to the CLI tool
    "brane-cli",

    # These crates directly relate to the `branec` tool
    "brane-cc",


    ### SERVICES ###
    # These crates implement services for central nodes
    "brane-drv",
    "brane-plr",
    "brane-api",

    # These crates implement services for worker nodes
    "brane-job",
    "brane-reg",
    "brane-chk",
    "brane-let",    # Not a service, container-local binary

    # These crates implement services that occur on any type of node
    "brane-prx",


    ### C-INTERFACES ###
    # These crates provide C-compatible interfaces to other libraries
    "brane-cli-c",


    ### LIBRARIES ###
    # These crates provide the full BraneScript/Bakery/... stack
    "brane-tsk",
    "brane-exe",
    "brane-ast",
    "brane-dsl",

    # These crates provide specifications / general implementations
    "brane-cfg",
    "brane-shr",
    "specifications",

    # # TODO
    # "brane-log",

    "xtask",
]



[workspace.package]
version = "3.0.0"
edition = "2021"
authors = [ "Onno Valkering", "Tim Müller" ]
description = "The Brane Framework is a workflow execution system that is capable of dealing with sensitive dataset. Created for the [EPI project](https://enablingpersonalizedinterventions.nl)."
repository = "https://github.com/braneframework/brane"
documentation = "https://wiki.enablingpersonalizedinterventions.nl"
license = "Apache-2.0"

[workspace.dependencies]
# Lut99 Crates
humanlog = { git = "https://github.com/Lut99/humanlog-rs", tag = "v0.2.0" }
enum-debug = { git = "https://github.com/Lut99/enum-debug", tag = "v1.1.0", features = ["derive"] }
error-trace = "3.3.1"
transform = { git = "https://github.com/Lut99/transform-rs", tag = "v0.2.0" }
names = { git = "https://github.com/Lut99/names-rs", tag = "v0.1.0", default-features = false, features = [ "rand", "three-lowercase" ]}
download = { git = "https://github.com/Lut99/download-rs", tag = "v0.1.0", default-features = false, features = ["download"] }

# Note: This does not use any root store by default. This will have to be enabled *explicitly* by the workspace member.
reqwest = { version = "0.12.0", features = ["rustls-tls-manual-roots"], default-features = false }

# Other BraneFramework / EPI dependencies
policy-reasoner = { git = "https://github.com/BraneFramework/policy-reasoner.git" }
policy-store = { git = "https://github.com/BraneFramework/policy-store.git" }

[workspace.lints.clippy]
result_large_err = { level = "allow", priority = 1 }
suspicious = "deny"

[patch."https://github.com/BraneFramework/policy-reasoner"]
# NOTE: Double slash is necessary because of: https://github.com/rust-lang/cargo/issues/5478
policy-reasoner = { git = "https://github.com//BraneFramework/policy-reasoner.git", rev = "b7ff17c" }
