version: '3'

services:
  brane-api:
    build: ./brane-api
    depends_on:
      - kafka
      - postgres
    ports:
      - 8080:8080

  brane-loop:
    build: ./brane-loop
    depends_on:
      - kafka
      - postgres
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock

  jupyterlab:
    build: ./brane-ide/jupyterlab
    command: ["jupyter", "lab", "--allow-root", "--LabApp.token=''"]
    ports:
      - 8888:8888

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      CONFLUENT_SUPPORT_METRICS_ENABLE: 0

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  registry:
    image: registry:2
    ports:
      - 5000:5000

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
