version: '3.6'

services:
  ###############
  ## AUXILLARY ##
  ###############

  # Database that contains package metadata
  aux-scylla:
    image: aux-scylla:${BRANE_VERSION:-latest}
    # ports:
    #   - "127.0.0.1:9042:9042"
    command: --smp 1
    restart: always
    labels:
    - kompose.service.type=nodeport
    - kompose.service.nodeport.port=9042

  # Handles events and callbacks throughout the framework
  aux-kafka:
    image: aux-kafka:${BRANE_VERSION:-latest}
    # ports:
    # - "127.0.0.1:9092:9092"
    restart: always
    environment:
      ZOOKEEPER_HOST: aux-zookeeper
      ZOOKEEPER_PORT: 2181
    labels:
    - kompose.service.type=nodeport
    - kompose.service.nodeport.port=9092

  # Zookeeper for Kafka
  aux-zookeeper:
    image: aux-zookeeper:${BRANE_VERSION:-latest}
    restart: always

  # # Xenon scheduler, which allows the framework to act as its own domain-local scheduler
  # brane-xenon:
  #   image: aux-xenon:${BRANE_VERSION:-latest}
  #   # ports:
  #   #   - "127.0.0.1:50054:50054"
  #   command: -v
  #   restart: always
  #   labels:
  #   - kompose.service.type=nodeport
  #   - kompose.service.nodeport.port=50054



  ###########
  ## BRANE ##
  ###########

  # "Proxy" service that can be targeted by local connections to be proxied (and encrypted with client auth) to remote hosts.
  brane-prx:
    image: brane-prx:${BRANE_VERSION:-latest}
    container_name: ${PRX_NAME:-brane-prx}
    command: --debug
    restart: always
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${PROXY:-}:${PROXY:-}
    - ${CERTS}:${CERTS}

  # The service in charge of package registry, downloading, uploading, etc
  brane-api:
    image: brane-api:${BRANE_VERSION:-latest}
    container_name: ${API_NAME:-brane-api}
    command: --debug
    restart: always
    ports:
    - "0.0.0.0:${API_PORT}:${API_PORT}"
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${INFRA}:${INFRA}
    - ${CERTS}:${CERTS}
    - ${PACKAGES}:${PACKAGES}
    depends_on:
    - aux-scylla
    - brane-prx
    # - aux-registry
    labels:
    - kompose.service.type=nodeport
    - kompose.service.nodeport.port=50051

  # The service that accepts client connections and executes workflow control flow
  brane-drv:
    image: brane-drv:${BRANE_VERSION:-latest}
    container_name: ${DRV_NAME:-brane-drv}
    command: --debug
    restart: always
    ports:
    - "0.0.0.0:${DRV_PORT}:${DRV_PORT}"
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${INFRA}:${INFRA}
    depends_on:
    - aux-kafka
    - brane-prx
    - brane-api
    labels:
    - kompose.service.type=nodeport
    - kompose.service.nodeport.port=50053

  # # The service logging everything
  # brane-log:
  #   image: brane-log:${BRANE_VERSION:-latest}
  #   container_name: brane-log
  #   ports:
  #   - "127.0.0.1:50055:50055"
  #   restart: always
  #   environment:
  #     BROKERS: "aux-kafka:9092"
  #     EVENT_TOPIC: job-evt
  #     SCYLLA: "aux-scylla:9042"
  #   depends_on:
  #   - aux-kafka
  #   labels:
  #   - kompose.service.type=nodeport
  #   - kompose.service.nodeport.port=50055

  # The service that chooses the appropriate domain to run a job on
  brane-plr:
    image: brane-plr:${BRANE_VERSION:-latest}
    container_name: ${PLR_NAME:-brane-plr}
    command: --debug
    restart: always
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${INFRA}:${INFRA}
    depends_on:
    - aux-kafka

networks:
  default:
    name: brane-central
