services:
  ###############
  ## AUXILLARY ##
  ###############

  # Nothing yet



  ###########
  ## BRANE ##
  ###########

  # "Proxy" service that can be targeted by local connections to be proxied (and encrypted with client auth) to remote hosts.
  brane-prx:
    image: brane-prx:${BRANE_VERSION:-latest}
    container_name: ${PRX_NAME:-brane-prx}
    command: --debug
    restart: always
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${PROXY:-}:${PROXY:-}
    - ${CERTS}:${CERTS}
    extra_hosts:
    - host.docker.internal:host-gateway

  # The service in charge of policy
  brane-chk:
    image: brane-chk:${BRANE_VERSION:-latest}
    init: true
    container_name: ${CHK_NAME:-brane-chk}
    ports:
    - "0.0.0.0:${CHK_DELIB_PORT}:${CHK_DELIB_PORT}"
    - "0.0.0.0:${CHK_STORE_PORT}:${CHK_STORE_PORT}"
    restart: always
    environment:
    - NODE_CONFIG_PATH=/home/brane/node.yml
    - POLICY_DB_PATH=/home/brane/policy.db
    - POLICY_DELIB_KEYS_PATH=/home/brane/delib_keys.json
    - POLICY_STORE_KEYS_PATH=/home/brane/store_keys.json
    - DELIB_ADDRESS=0.0.0.0:${CHK_DELIB_PORT}
    - STORE_ADDRESS=0.0.0.0:${CHK_STORE_PORT}
    volumes:
    - ${NODE_CONFIG_PATH}:/home/brane/node.yml
    - ${POLICY_DB}:/home/brane/policy.db
    - ${POLICY_DELIB_KEYS}:/home/brane/delib_keys.json
    - ${POLICY_STORE_KEYS}:/home/brane/store_keys.json
    extra_hosts:
    - host.docker.internal:host-gateway

  # The service in charge of the local container- and data registry
  brane-reg:
    image: brane-reg:${BRANE_VERSION:-latest}
    container_name: ${REG_NAME:-brane-reg}
    command: --debug --delib-token "${CHECKER_DELIB_TOKEN}"
    ports:
    - "0.0.0.0:${REG_PORT}:${REG_PORT}"
    restart: always
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${BACKEND}:${BACKEND}
    - ${CERTS}:${CERTS}
    - ${DATA}:${DATA}
    - ${RESULTS}:${RESULTS}
    extra_hosts:
    - host.docker.internal:host-gateway

  # The service that is the 'main' service on the worker.
  brane-job:
    image: brane-job:${BRANE_VERSION:-latest}
    container_name: ${JOB_NAME:-brane-job}
    command: --debug --delib-token "${CHECKER_DELIB_TOKEN}"
    ports:
    - "0.0.0.0:${JOB_PORT}:${JOB_PORT}"
    restart: always
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${BACKEND}:${BACKEND}
    - ${CERTS}:${CERTS}
    - ${PACKAGES}:${PACKAGES}
    - ${DATA}:${DATA}
    - ${RESULTS}:${RESULTS}
    - ${TEMP_DATA}:${TEMP_DATA}
    - ${TEMP_RESULTS}:${TEMP_RESULTS}
    - /var/run/docker.sock:/var/run/docker.sock:uid=1000
    extra_hosts:
    - host.docker.internal:host-gateway

networks:
  default:
    name: brane-worker-${LOCATION_ID}
