[package]
name = "brane"
version = "0.1.0"
authors = ["Onno Valkering"]
edition = "2018"

[dependencies]
appdirs = "0.2"
chrono = "0.4"
console = "0.11"
crc32fast = "1.2"
cwl = { git = "https://github.com/onnovalkering/cwl-rs" }
brane-dsl = { path = "../brane-dsl" }
brane-vm = { path = "../brane-vm" }
dialoguer = "0.6"
env_logger = "0.7"
failure = "0.1"
flate2 = "1.0"
human-panic = "1.0"
hyper = "0.13"
indicatif = "0.14"
linefeed = "0.6"
log = "0.4"
prettytable-rs = "0.8"
reqwest = {version = "0.10", features = ["json", "stream"] }
semver = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
specifications = { path = "../specifications" }
tar = "0.4"
tokio = { version = "0.2", features = ["full"] }
tokio-util = "0.3"
yaml-rust = "0.4"
