[package]
name = "brane-log"
version = { workspace = true }
authors = { workspace = true }
edition = "2018"
rust-version = "1.74.1"

[dependencies]
anyhow = "1"
async-stream = "0.3"
bincode = "1.3"
bytes = "1"
clap = { version = "4.0.24", features = ["derive","env"] }
derive_more = "0.99"
dotenvy = "0.15"
env_logger = "0.10"
futures = "0.3"
juniper = "0.15"
juniper_graphql_ws = "0.3"
juniper_warp = { version = "0.7", features = ["subscriptions"] }
log = "0.4"
prost = "0.11"
rdkafka = { version = "0.31", features = ["cmake-build"] }
scylla = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
