[package]
name = "brane-bvm"
version = "0.5.0"
authors = ["Onno Valkering", "Tim Müller"]
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1"
bollard = "0.11"
broom = "0.3"
bytes = "1"
fnv = "1.0"
futures = "0.3"
itertools = "0.10"
log = "0.4"
rayon = "1.5"
serde_json = "1.0.78"
smallvec = "1.6"
specifications = { path = "../specifications" }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
brane-dsl = { path = "../brane-dsl" }
criterion = { version = "0.3", features = ["async", "async_futures"] }

[[bench]]
name = "fibonacci"
harness = false
