[package]
name = "executor"
version = "0.1.0"
authors = ["Onno Valkering"]
edition = "2018"

[dependencies]
actix-rt = "1.0"
actix-web = "2.0"
env_logger = "0.7"
failure = "0.1"
futures = "0.3"
k8s-openapi = { version = "0.7", features = ["v1_15"] }
kube = "0.28"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
uuid = { version = "0.4", features = ["v4"] }