locations:
  vm:
    kind: local
    network: kind
    registry: "localhost:5000"
    callback_to: "http://brane-clb:50052"
    mount_dfs: "redis://redis"

  k8s:
    kind: kube
    address: brane-control-plane
    namespace: brane
    registry: "localhost:5000"
    callback_to: "http://brane-clb:50052"
    mount_dfs: "redis://redis"
    credentials:
      mechanism: config
      file: s$K8S_CONFIG_FILE

  hpc:
    kind: slurm
    address: slurm:22
    runtime: singularity
    registry: "registry:5000"
    callback_to: "http://brane-clb:50052"
    mount_dfs: "redis://redis"
    credentials:
      mechanism: ssh-password
      username: s$HPC_USERNAME
      password: s$HPC_PASSWORD
