locations:
  # The name of the Kubernetes infrastructure
  kube:
    # It's a Kubernetes cluster
    kind: kube

    # The endpoint of the remote cluster. Replace this with the relevant address.
    # Note: is relative to containers (so localhost won't work!!)
    address: <infra_addr>:6443

    # The namespace where brane jobs will be ran.
    # Needn't be the same as any other namespace, but should exist on the cluster and be accessible by the account used by Brane.
    namespace: brane

    # The endpoint of the Docker registry. Replace with the address of the node (or cluster) where the control plane is running.
    # Note: is relative to containers (so localhost won't work!!)
    registry: "<control_addr>:50050"

    # The endpoint of the brane-clb service. This address should point to the node (or cluster) where the control plane is running.
    # Note: is relative to containers (so localhost won't work!!)
    callback_to: "http://<control_addr>:50052"

    # The endpoint for the distributed filesystem mount. This address should point to the node (or cluster) where the control plane is running.
    # Note: is relative to containers (so localhost won't work!!)
    mount_dfs: "redis://<control_addr>"

    # Provides the credentials for accessing the cluster.
    # The credentials are provided using a Kubernetes config. Check this (https://computingforgeeks.com/restrict-kubernetes-service-account-users-to-a-namespace-with-rbac/) tutorial to see how to setup one that only accesses a particular namespace.
    credentials:
      mechanism: config
      # Note: this refers to an entry in `secrets.yml` called 'k8s-config'. You should add the generated config there (since it contains sensitive tokens and certificates).
      # Also note: the secrets file only accepts base64-encoded stuff, so be sure to encode it like that first.
      file: s$k8s-config
