[package]
name = "brane-cc"
rust-version = "1.81"
edition = "2021"
authors = [ "Tim Müller" ]
version.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "branec"
path = "src/main.rs"

[dependencies]
dotenvy = "0.15.0"
human-panic = "2.0.0"
thiserror = "2.0.0"
tokio = { version = "1.38.0", features = ["rt","macros"] }
url = "2.5.0"

# Workspace dependencies
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
enum-debug.workspace = true

brane-ast = { path = "../brane-ast" }
brane-dsl = { path = "../brane-dsl" }
brane-shr = { path = "../brane-shr" }
brane-tsk = { path = "../brane-tsk" }
serde_json = "1.0.120"
specifications = { path = "../specifications" }


[target.'cfg(unix)'.dependencies]
expanduser = "1.2.2"

[lints]
workspace = true
