[package]
name = "brane-job"
version = "0.4.0"
authors = ["Onno Valkering"]
edition = "2018"

[dependencies]
anyhow = "1"
brane-cfg = { path = "../brane-cfg" }
bytes = "1"
clap = "3.0.0-beta.2"
dotenv = "0.15"
env_logger = "0.8"
futures = "0.3"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
kube = "0.51"
log = "0.4"
prost = "0.7"
rdkafka = { version = "0.25", features = ["cmake-build"] }
tokio = { version = "1", features = ["full"] }
xenon-rs = "0.3"
