apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent
  labels:
    app: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluent
  template:
    metadata:
      labels:
        app: confluent
    spec:
      containers:
        - name: cp-kafka
          image: confluentinc/cp-kafka:5.5.1
          ports:
            - containerPort: 9092        
          env:
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "confluent:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://confluent:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
            - name: CONFLUENT_SUPPORT_METRICS_ENABLE
              value: "0"

        - name: cp-zookeeper
          image: confluentinc/cp-zookeeper:5.5.1
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
