apiVersion: v1
kind: Service
metadata:
  name: confluent
  labels:
    app: confluent
spec:
  selector:
    app: confluent
  ports:
    - name: cp-kafka
      port: 9092
      targetPort: 9092
    - name: cp-zookeeper
      port: 2181
      targetPort: 2181      