apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: vault-ext
  labels:
    app: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 31993  
