[package]
name = "brane-chk"
version.workspace = true
edition.workspace = true
authors = [ "Tim Müller" ]
description = "Implements the famous checker, which reasons about policies and restricts the system."
repository.workspace = true
documentation.workspace = true


[dependencies]
enum-debug = { git = "https://github.com/Lut99/enum-debug", features = ["derive"] }
log = "0.4"
transform = { git = "https://github.com/Lut99/transform-rs" }

brane-ast = { path = "../brane-ast" }
brane-shr = { path = "../brane-shr" }
specifications = { path = "../specifications" }


[dev-dependencies]
clap = { version = "4.4", features = ["derive"] }
error-trace = { git = "https://github.com/Lut99/error-trace-rs" }
humanlog = { git = "https://github.com/Lut99/humanlog-rs" }
log = "0.4"
serde_json = "1.0"
