[package]
name = "brane-api"
version = "0.1.0"
authors = ["Onno Valkering"]
edition = "2018"

[dependencies]
actix-multipart = "0.2"
actix-rt = "1"
actix-web = "2"
chrono = "0.4"
crc32fast = "1.2"
env_logger = "0.7"
failure = "0.1"
flate2 = "1.0"
futures = "0.3"
log = "0.4"
diesel = { version = "1.4", features = ["r2d2", "sqlite", "chrono"] }
diesel_migrations = "1.4"
dotenv = "0.15"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
specifications = { path = "../specifications" }
structopt = "0.3"
tar = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }

