[package]
name = "brane-api"
version = "0.1.0"
authors = ["Onno Valkering"]
edition = "2018"

[dependencies]
actix-web = "2"
actix-rt = "1"
env_logger = "0.7"
failure = "0.1"
futures = "0.3"
log = "0.4"
diesel = { version = "1.4", features = ["r2d2", "sqlite"] }
dotenv = "0.15"
structopt = "0.3"
