openapi: 3.0.3
info:
  title: v6_client
  version: 1.0.0
  description: The Vantage6 API.

paths:
  "/api/collaboration":
    get:
      operationId: get_collaborations
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK, array of collaborations
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Collaboration"
    post:
      operationId: create_collaboration
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - organization_ids
              properties:
                name:
                  type: string
                organization_ids:
                  type: string
      responses:
        "200":
          description: OK, created collaboration
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Collaboration"

  "/api/node":
    get:
      operationId: get_nodes
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK, array of nodes
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Node"
    post:
      operationId: create_node
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - collaboration_id
              properties:
                collaboration_id:
                  type: integer   
      responses:
        "200":
          description: OK, created node
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Node"               
                      
  "/api/token/user":
    post:
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/User"
      responses:
        '200':
          description: OK, authenticated
          content:
            application/json:
              schema:
                type: object
                required:
                  - access_token
                  - refresh_token
                  - refresh_url
                  - user_url
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  refresh_url:
                    type: string
                  user_url:
                    type: string

components:
  schemas:
    Collaboration:
      properties:
        id:
          type: integer
        name:
          type: string
        encrypted:
          type: boolean

    Node:
      properties:
        api_key:
          type: string      
        id:
          type: integer
        ip:
          type: string
        name:
          type: string
        type:
          type: string
        
    User:
      properties:
        username:
          type: string
        password:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
