apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: brane-api
          image: onnovalkering/brane-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

        - name: brane-loop
          image: onnovalkering/brane-loop
          imagePullPolicy: Always

        - name: jupyterlab
          image: onnovalkering/brane-jupyterlab
          command: ["jupyter", "lab", "--allow-root", "--LabApp.token=''"]
          ports:
            - containerPort: 8888

        - name: kafka
          image: confluentinc/cp-kafka:5.5.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_NUM_PARITIONS
              value: "3"
            - name: CONFLUENT_SUPPORT_METRICS_ENABLE
              value: "0"

        - name: postgres
          image: postgres:12
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres

        - name: redis
          image: redis:6-alpine
          ports:
            - containerPort: 6379
        
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000

        - name: vault
          image: vault:1.5.3
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: mytoken

        - name: xenon
          image: onnovalkering/xenon-grpc
          ports:
            - containerPort: 50051

        - name: zookeeper
          image: confluentinc/cp-zookeeper:5.5.1
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
