apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    service: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
    service: {{ .Release.Name }}-api
spec:
  selector:
    app: brane-api
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jupyterlab
  labels:
    app: {{ .Release.Name }}-jupyterlab
    service: {{ .Release.Name }}-jupyterlab
spec:
  selector:
    app: jupyterlab
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    app: {{ .Release.Name }}-registry
    service: {{ .Release.Name }}-registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000      
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault
  labels:
    app: {{ .Release.Name }}-vault
    service: {{ .Release.Name }}-vault
spec:
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
      