[package]
name = "brane-ctl"
version = { workspace = true }
edition = "2021"
authors = [ "Tim Müller" ]

[[bin]]
name = "branectl"
path = "src/main.rs"

[dependencies]
base64ct = "1.6"
bollard = "0.14"
clap = { version = "4.0.24", features = ["derive","env"] }
console = "0.15"
diesel = { version = "2.1", features = ["sqlite"] }
diesel_migrations = "2.1"
dirs-2 = "3.0"
dotenvy = "0.15"
enum-debug = { git = "https://github.com/Lut99/enum-debug", features = ["derive"] }
# env_logger = "0.10"
hex-literal = "0.4"
humanlog = { git = "https://github.com/Lut99/humanlog-rs" }
human-panic = "1.0"
lazy_static = "1.4.0"
log = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
shlex = "1.1.0"
tempfile = "3.3.0"
tokio = { version = "1", features = [] }

brane-cfg = { path = "../brane-cfg" }
brane-shr = { path = "../brane-shr" }
brane-tsk = { path = "../brane-tsk" }
specifications = { path = "../specifications" }


# Hacky indeed but necessary to dodge OpenSSL linking, which we need to make cross-compilation _so_ much easier
[dependencies.openssl-sys]
features = ["vendored"]
