[package]
name = "brane-std"
version = "0.3.0"
authors = ["Onno Valkering"]
edition = "2018"

[dependencies]
anyhow = "1.0"
brane-sys = { path = "../brane-sys" }
lazy_static = "1.4"
log = "0.4"
rand = "0.7"
url = "2.1"
specifications = { path = "../specifications" }
