[package]
name = "brane-shr"
version = "0.6.0"
authors = ["Onno Valkering", "Tim Müller"]
edition = "2018"

[dependencies]
anyhow = "1"
num-derive = "0.2"
num-traits = "0.2"
regex = "1.5"
specifications = { path = "../specifications" }
url = "2.2"
