[package]
name = "overview"
description = "Dummy crate for having a nice entrypoint in the generated docs."
rust-version = "1.64.0"
edition = "2021"
version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
