[package]
name = "overview"
description = "Dummy crate for having a nice entrypoint in the generated docs."
edition = "2021"
rust-version = "1.64"
version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
