[package]
name = "brane-oas"
version = "0.3.0"
authors = ["Onno Valkering"]
edition = "2018"

[dependencies]
anyhow = "1"
maplit = "1"
openapiv3 = "0.4"
serde = "1"
serde_json = "1"
serde_yaml = "0.8"
specifications = { path = "../specifications" }
