name: brane-exec

on: [push]

jobs:
  unit-tests:
    name: unit-tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build project
        working-directory: brane-exec
        run: cargo build -v

      - name: Run unit tests
        working-directory: brane-exec
        run: cargo test -v --lib
