name: CD

on:
  create:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: sudo apt-get install -y libpq-dev libssl-dev musl-tools

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: x86_64-unknown-linux-musl
            override: true

      - name: Run unit tests (optimized)
        run: cargo test -v --lib --release

      - name: Build binaries (optimized)
        run: |
          cargo build -v --release --package brane-cli
          cargo build -v --release --package brane-let --target x86_64-unknown-linux-musl

      - name: Create release
        uses: anton-yurchenko/git-release@v3
        env:
          ALLOW_TAG_PREFIX: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
            target/release/brane-cli
            target/x86_64-unknown-linux-musl/release/branelet
