name: Cargo Check

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      rust-version:
        required: false
        type: string
      packages:
        required: true
        type: string
      cache:
        required: false
        type: boolean
        default: false

jobs:
  cargo-check:
    name: "${{ inputs.packages }} / ${{ inputs.os }}"
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Override active rustup toolchain
        if: inputs.rust-version != ''
        run: echo "RUSTUP_TOOLCHAIN=${{ inputs.rust-version }}" >> $GITHUB_ENV

      - name: Show toolchain
        run: rustup show active-toolchain

      - name: Install dependencies
        if: startsWith(inputs.os, 'ubuntu-')
        run: sudo apt update && sudo apt install -y libsqlite3-dev

      - name: Install Cargo Hack
        uses: taiki-e/install-action@cargo-hack

      - name: Cache dependencies
        if: inputs.cache
        uses: Swatinem/rust-cache@v2

      - name: Check project (Workspace)
        if: inputs.packages == 'workspace'
        run: cargo hack --feature-powerset check --workspace

      - name: Check project (Frontend)
        if: inputs.packages == 'frontend'
        run: cargo hack --feature-powerset check --package brane-cli --package brane-cc --package brane-cli-c
