name: Release

on:
  create:
    tags:
      - 'v*'

jobs:
  build-linux-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install musl
        run: sudo apt update && sudo apt-get install -y musl-tools

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.54.0
            target: x86_64-unknown-linux-musl
            override: true

      - name: Build (optimized) binaries
        run: |
          cargo build -v --release --package brane-cli
          mv target/release/brane-cli target/release/brane-linux

          cargo build -v --release --package brane-let --target x86_64-unknown-linux-musl

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: |
            target/release/brane-linux
            target/x86_64-unknown-linux-musl/release/branelet

  build-darwin-binaries:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.54.0
            override: true

      - name: Build (optimized) binaries
        run: |
          cargo build -v --release --package brane-cli
          mv target/release/brane-cli target/release/brane-darwin

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: darwin
          path: |
            target/release/brane-darwin
  
  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-linux-binaries
      - build-darwin-binaries
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Create release
        uses: anton-yurchenko/git-release@v3
        env:
          ALLOW_TAG_PREFIX: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
            artifacts/darwin/brane-darwin
            artifacts/linux/brane-linux
            artifacts/linux/branelet

